import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import ImageTextSection from '@/components/ui/ImageTextSection';
import CenteredIntro from '@/components/ui/CenteredIntro';
import ExperienceSection from '@/components/ui/ExperienceSection';
import SkillsetSection from '@/components/ui/SkillsetSection';




// 1. Import the Font Awesome CSS file
import '@fortawesome/fontawesome-svg-core/styles.css';
// 2. Import the config object
import { config } from '@fortawesome/fontawesome-svg-core';
// 3. Tell Font Awesome to not inject its own CSS automatically.
config.autoAddCss = false;


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
        className="antialiased min-h-screen" // Removed the bg-[...] class
        style={{
          backgroundImage: "conic-gradient(at top right, #02031aff 0%, #360f4dff 40%, #010824ff 66%, #020220ff 100%)"
        }}>
        <Header />
        <ImageTextSection />
        <CenteredIntro />
        <ExperienceSection />
        <SkillsetSection />
        {children}
      </body>
    </html >
  );
}
